name: Cypress

on:
    push:
        branches: [master]

jobs:
    Run_test:
        runs-on: ubuntu-20.04 # Choosing OS
        strategy:
            matrix:
                node-version: [18]
          
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm i npm@latest
            - run: npm i
            - name: run test
              run: npm run cy:headless:chrome

            - name: Get Allure history
              uses: actions/checkout@v2
              if: always()
              continue-on-error: true
              with:
                  ref: gh-pages
                  path: gh-pages

            - name: Allure Report action from marketplace
              uses: simple-elf/allure-report-action@master
              if: always()
              with:
                  allure_results: allure-results
                  gh_pages: gh-pages
                  allure_report: allure-report
                  allure_history: allure-history
                  keep_reports: 20

            - name: Deploy report to Github Pages
              if: always()
              uses: peaceiris/actions-gh-pages@v2
              env:
                  PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PUBLISH_BRANCH: gh-pages
                  PUBLISH_DIR: allure-history